### ISSUE TITLE
Issue when starting flask

### ISSUE THREAD

**Issue by glemaitre** [covid19-dash/covid-dashboard#15]
It seems that we introduce a breaking change there:

https://github.com/covid19-dash/covid-dashboard/runs/509621343

We cannot start anymore flask I assume. Any Idea?

ping @GaelVaroquaux @emmanuelle

**Comment by GaelVaroquaux** [comment]
We think that it is because the server is now more complex, and takes
longer to start. @emmanuelle is investigating adding more delay.

**Comment by glemaitre** [comment]
OK I pushed a commit to add the dependency. Would it be better to start gunicorn instead of the flask testing server or because we don't serve any request it will not be helpful?

**Comment by emmanuelle** [comment]
Yes `gunicorn` is what is used usually for example when pushing to heroku

**Comment by GaelVaroquaux** [comment]
This is fixed.
