### ISSUE TITLE
Add different symbols for different countries, for better visibility

### ISSUE THREAD

**Issue by emmanuelle** [covid19-dash/covid-dashboard#18]
https://plot.ly/python/marker-style/#custom-marker-symbols

choose a different cycle length as for colors so that we have a unique (color, symbol) tuple for each country

**Comment by emmanuelle** [comment]
This corresponds to this part https://github.com/covid19-dash/covid-dashboard/blob/master/make_figures.py#L73 of the code.

**Comment by ashwinpn** [comment]
Can I work on this??

**Comment by GaelVaroquaux** [comment]
@ashwinpn yes: this would be great!

**Comment by ashwinpn** [comment]
Cool, will create a PR as soon as I am done. Has Circle CI been added, as of now?

**Comment by GaelVaroquaux** [comment]
I'm not sure Circiel CI is working yet (@glemaitre is working on it right now). I'll just checkout your branch and run it locally).

**Comment by GaelVaroquaux** [comment]
Fixed by #60
