### ISSUE TITLE
Add Circle-CI and storage of the artifacts to be able to review pull requests

### ISSUE THREAD

**Issue by GaelVaroquaux** [covid19-dash/covid-dashboard#21]
One challenge is going to be that the dash app hardcode all paths of its components as to the root of the URL ('/assets/styles.css').

Once the CircleCI works, we should use the artifact redirector:
https://github.com/marketplace/actions/run-circleci-artifacts-redirector

**Comment by glemaitre** [comment]
I can take a look at it tomorrow night

**Comment by glemaitre** [comment]
@GaelVaroquaux Could you give some admin access to the organization level to activate circleci.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux Could you give some admin access to the organization level to activate circleci.

Done!

**Comment by glemaitre** [comment]
Thanks, I made the first PR to activate de service. I will correct if there are some issues and add the github action to access the artefacts.

**Comment by GaelVaroquaux** [comment]
Awesome work!!! This is so useful!!
