### ISSUE TITLE
Normalize time evolution

### ISSUE THREAD

**Issue by emmanuelle** [covid19-dash/covid-dashboard#3]
Can normalize by
- dividing number of cases by country population
- plotting against time - t100, where t100 is the time when case nb 100 was detected. What should be do for countries will less than 100 cases? Drop them probably.

**Comment by GaelVaroquaux** [comment]
To divide by the population of the country, a first thing would be to build a table of these. I suspect that yago or dbdebia maybe useful to retrieve such table. Or just finding this table somewhere? :)

**Comment by GaelVaroquaux** [comment]
Basic scaling is implemented. Closing.
