### ISSUE TITLE
Larger font in legend

### ISSUE THREAD

**Issue by GaelVaroquaux** [covid19-dash/covid-dashboard#35]
The legend of the time series could use a larger font.

And maybe, ideally, it should be moved below the figure, to be able to have a larger figure.

**Comment by GaelVaroquaux** [comment]
Legend position fixed in master. Not font size

**Comment by emmanuelle** [comment]
for the position, we can also have it below the figure, by restricting the domain of the plot. As you wish

**Comment by GaelVaroquaux** [comment]
> for the position, we can also have it below the figure, by restricting the domain of the plot. As you wish

So far, I think that the current situation is fine. It helps having a
larger dynamical range vertically not to have it below.

**Comment by emmanuelle** [comment]
ok, I'm currently fixing the font size

**Comment by emmanuelle** [comment]
addressed in #38
