### ISSUE TITLE
legend positioning for log scale

### ISSUE THREAD

**Issue by poldrack** [covid19-dash/covid-dashboard#41]
the legend is covering up some of the data in log scale mode 

![image](https://user-images.githubusercontent.com/871056/76890707-14401e80-6845-11ea-811c-df4e85cde97d.png)

**Comment by poldrack** [comment]
this is still happening:
![image](https://user-images.githubusercontent.com/871056/76981206-7d806a00-68f7-11ea-95d5-613a7917f3a1.png)

**Comment by emmanuelle** [comment]
Yes :-(. See https://twitter.com/robroc/status/1240745001312825344?s=21
Will work on it tonight.
