### ISSUE TITLE
numbers cut off to right

### ISSUE THREAD

**Issue by poldrack** [covid19-dash/covid-dashboard#46]
depending on the screen size, the numbers on the right get cramped or cut off. maybe add some kind of padding to right of the table?
![ProblemWithResizingScreen](https://user-images.githubusercontent.com/871056/76902092-75bdb880-6858-11ea-8892-5daaec377e94.jpg)

**Comment by emmanuelle** [comment]
I think the 70% here https://github.com/covid19-dash/covid-dashboard/blob/master/app.py#L104 is a bit too much, for a small screen 60% would give better results.

**Comment by GaelVaroquaux** [comment]
This was solved by @emmanuelle
