### ISSUE TITLE
collision between buttons and hover menu above plot

### ISSUE THREAD

**Issue by poldrack** [covid19-dash/covid-dashboard#47]
depending on sizing, the hover menu above the graph sometimes collides with the log/linear buttons
![ProblemWithMenuHover](https://user-images.githubusercontent.com/871056/76902163-9ede4900-6858-11ea-9c9d-e824ed15064e.jpg)

**Comment by GaelVaroquaux** [comment]
We should simplify this modebar as in #53 : I'm in favor of removing the "box select", "lasso select", "home" (autoscale axes does the same thing) and "toggle spike lines" buttons.

**Comment by emmanuelle** [comment]
addressed in #53
