### ISSUE TITLE
Automate deployment to GH pages

### ISSUE THREAD

**Issue by emmanuelle** [covid19-dash/covid-dashboard#5]
Add Github action to deploy to github pages.

Needs to use the Makefile to transform dash app pages into a static site.

**Comment by glemaitre** [comment]
I would be happy to give a hand on this one.

**Comment by GaelVaroquaux** [comment]
Thanks a lot! Do you need access to the repo?

**Comment by glemaitre** [comment]
I think so.

**Comment by GaelVaroquaux** [comment]
OK, I'm on it.

**Comment by emmanuelle** [comment]
Thank you @glemaitre :-). The current workflow is in the Makefile, it consists of 
- a hack to transform a Dash app into static html pages (`make html`)
- and pushing these pages to github pages (`make gh-pages`).
Please be in touch if you have questions :-)

**Comment by glemaitre** [comment]
So the deployment should happen at each merge of a PR in master?

**Comment by emmanuelle** [comment]
yes. Soon enough we will switch to a pull-request mode so we'll be able to check that the changes should not break the deployment.

**Comment by GaelVaroquaux** [comment]
@glemaitre : did you get the invitation for the repo?

**Comment by emmanuelle** [comment]
Please note that https://github.com/covid19-dash/covid-dashboard/commit/b2ce5a9ae32b7f2386d4bd10f2ecad4ae48459b2 added one line to the Makefile.

**Comment by glemaitre** [comment]
Yes. I am trying to deploy on my fork before to make a PR here. I am the config of the token for automatic push so it should be soonish working.

**Comment by GaelVaroquaux** [comment]
Exciting!!

If it's easier for you, do not hesitate to push to master. We are still
at early stages of the project.

**Comment by glemaitre** [comment]
So it should normally push in `gh-pages` now.

In short, I made a `make html` and push the content of the localhost to `gh-pages` when there is a push on `master`. We should check that we have the right content.

If something else need to be configure, I relied on the following github-action: https://github.com/peaceiris/actions-gh-pages

**Comment by glemaitre** [comment]
I assume that when we are happy with the current results we can push to the repository of the website. This should not be a big deal. We need to setup to wish repository to push: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository

**Comment by emmanuelle** [comment]
Thanks a lot ! I'll try it out when the little one is asleep :-). Good night ;-)

**Comment by glemaitre** [comment]
OK, one thing strange (which is the reason I did not push in the website repo yet), I am getting a `Loading...`: https://covid19-dash.github.io/covid-dashboard/

But I think it should be due to the state of master rather than something weird on the deployment.

**Comment by glemaitre** [comment]
FYI:

We need to change the deploy section with:

```
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository:  covid19-dash/covid19-dash.github.io
          publish_branch: master
          publish_dir: ./127.0.0.1:8050
```

**Comment by glemaitre** [comment]
I set up the SSH keys so only the section needs to be changed. Feel free to change it during my sleep :)

**Comment by emmanuelle** [comment]
Hum this "Loading" thing can be due to Jekyll, I'll check whether the GH action pushes a `.nojekyll` file.

**Comment by GaelVaroquaux** [comment]
I think that the reason that this is not working is that the scripts and other components are referred too with a "/..." href.

If we deployed to the .github.io repo instead of the gh-pages of this repo, I think that it would work.

**Comment by GaelVaroquaux** [comment]
OK, this worked: the github action now works. Thank you very much @glemaitre !!
