### ISSUE TITLE
Add a cron to rebuild the site

### ISSUE THREAD

**Issue by GaelVaroquaux** [covid19-dash/covid-dashboard#56]
We should have a cron (do github action do that?) to rebuild the site daily. I think that John Hopkins releases new data approximately at the same hour. We should do it after. If not, something around 4pm NY times seems reasonable.

**Comment by punchagan** [comment]
It seems like the uploads are triggered at midnight GMT, based on the commits. Followed by some clean ups, which seem to be made manually. May be an hour after that? Or midnight NY time?

**Comment by GaelVaroquaux** [comment]
> May be an hour after that?

Sound right! Unless you think that the manual updates sometimes come
later.

**Comment by punchagan** [comment]
It does seem like manual updates come a little later, on some days. It depends on the data each day, I guess.

**Comment by GaelVaroquaux** [comment]
> It does seem like manual updates come a little later, on some days.

The big challenge of the updates is that sometimes the names of the
countries changes. It makes our cross-merging with other sources very
fragile. Are the manual updates related to country names?

**Comment by glemaitre** [comment]
I see 2 solutions here:

* a simple one by adding the following to the `deploy.yml`:

```yml
on:
  push:
    branches:
      - master
  schedule:
    - '0 1 * * *'  # run at during the 1st hour of each day
```

* to periodically check if there is a change in the data repository upstream. A viable solution is to store the commit hash in our repo and compare it. The following [SO thread](https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release) explains how to do that.

**Comment by GaelVaroquaux** [comment]
Thanks @glemaitre ! I propose that we start with the first, simple, one, and work later on the better one.
