### ISSUE TITLE
Add a text to explain the dynamics of the epidemic to the public

### ISSUE THREAD

**Issue by GaelVaroquaux** [covid19-dash/covid-dashboard#6]
We should have a markdown text that get included while building the app. The goal is to be didactic, raise awareness, but also be clear about the limitations of the data and of the models.

**Comment by poldrack** [comment]
I'm happy to get started on this.  where do you see it going? as a separate page, below visualization, or somehow integrated into the visualization? I first need to get my head around all of the data, at which point I can start putting together some ideas, but any suggestions are welcome.

**Comment by GaelVaroquaux** [comment]
Integrated as text below. But integration of text from md will be easy technically.

**Comment by emmanuelle** [comment]
I just added a `text_block.md` to the repo, if you edit it, it's integrated into the app. Thanks @poldrack  :-).

**Comment by poldrack** [comment]
thx!  I am going to edit the explanatory material in a separate file, because i'd prefer it to be vetted by an expert before it goes on the site, in case someone happens to point users to the draft site

**Comment by GaelVaroquaux** [comment]
Sounds good! We have the workflow to easily integrate it.

**Comment by emmanuelle** [comment]
Looks great @poldrack thank you so much! (I built locally on my machine, won't deploy until you give us a GO)
![Screenshot from 2020-03-14 16-56-48](https://user-images.githubusercontent.com/263366/76690310-1e7bd600-6615-11ea-8c72-fff9d716b2cc.png)

**Comment by GaelVaroquaux** [comment]
Fixed (so far).

**Comment by GaelVaroquaux** [comment]
Continuation in #27
