### ISSUE TITLE
Use pure.css to have a reactive layout.

### ISSUE THREAD

**Issue by GaelVaroquaux** [covid19-dash/covid-dashboard#7]
pure.css does not use javascript, hence it is well-suited to what we do. We should use its reactive engine to be mobile-friendly.

**Comment by DrGFreeman** [comment]
Hi @GaelVaroquaux an @emmanuelle, I'm interested to contribute in the development of a reactive layout using [Dash Bootstrap Components](https://dash-bootstrap-components.opensource.faculty.ai/).

**Comment by GaelVaroquaux** [comment]
The benefit of using pure is that there is no dependencies, and it's super simple.

I just commit a first version of a responsive design.

**Comment by GaelVaroquaux** [comment]
This is fixed reasonably well in the current website, using basic pure grid.
