### ISSUE TITLE
Add vertical line at last measurement date to show when the data stops

### ISSUE THREAD

**Issue by emmanuelle** [covid19-dash/covid-dashboard#76]
This would make it clearer when measurement data stops. 

How to do this: https://plot.ly/python/shapes/#lines-positioned-relative-to-the-plot--to-the-axes (xref=x, yref=paper).

**Comment by mrastgoo** [comment]
can I work on this ? 
and if I get it right the idea is to separate the current measurements and prediction with the vertical line yes ?

**Comment by emmanuelle** [comment]
Hi @mrastgoo , thanks! Yes the idea is to add a visual cue of the current date (or the last measurement point, there's a difference of at most one day between the two), I think at the moment it's a bit hard to see where we are. It should be quite thin, maybe dotted, so that it does not interfere with the timeseries.
