### ISSUE TITLE
Follow changes on the upstream data

### ISSUE THREAD

**Issue by GaelVaroquaux** [covid19-dash/covid-dashboard#80]
JHU has changed their data structure, and are no longer updating the files that we are pulling from:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

We can get up to date info on confirmed cases with the same structure here:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

However, to get the recovered cases (and hence the active), we need to pull the daily reports, rather than the time series, from here:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports
This means that we will have to build the time series ourselves, which is a bit more work.

**Comment by emmanuelle** [comment]
The first two links which you posted are the same, is it intentional?

**Comment by GaelVaroquaux** [comment]
Fixed in #81
